# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Monitor0

on:
  push:
  schedule:
    - cron: '49 14,15 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        sleep: ['1', '60', '120', '180', '240', '270', '300', '360', '420', '480', '540', '570', '600', '660', '720', '780', '840', '870', '900']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        python bot.py ${{ matrix.sleep }} ${{ secrets.TELEGRAM_TOKEN }} ${{ secrets.TELEGRAM_TO }}
