name: Monitor10

on:
  schedule:
    - cron: '10,25,40,55 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        sleep: ['1']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        python bot.py ${{ matrix.sleep }} ${{ secrets.TELEGRAM_TOKEN }} ${{ secrets.TELEGRAM_TO }}
