# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Monitor

on:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        sleep: ['1', '150', '300', '450', '600', '750', '900', '1050', '1200', '1350', '1500', '1650', '1800', '1950', '2100', '2250', '2400', '2550', '2700']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        python bot.py ${{ matrix.sleep }}
