# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Monitor0

on:
  schedule:
    - cron: '0,20,40 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
<<<<<<< HEAD
        sleep: ['1', '300', '600', '900', '1200']
=======
        sleep: ['0', '300', '600', '800']
>>>>>>> ca4b412a7c7c0a14527049b9ab05b0513e734a55
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        python bot.py ${{ matrix.sleep }} ${{ secrets.TELEGRAM_TOKEN }} ${{ secrets.TELEGRAM_TO }}
